
%% Plot solution

closeall

projFolderPath = "/Users/chuckjia/Documents/Workspace/Git/weather/";

solnameArray = ["theta", "qv", "qc", "qp"];
zlimitsArray = {[-50, 100], [0, 12], [0, 0.035], [0, 0.05]};
zlimitsMap = containers.Map(solnameArray, zlimitsArray);

solname = "theta";
zlimits = zlimitsMap(solname);
Dt = 0.5;
Nt = 200;


timesteps = 0:Dt:Nt*Dt;


plotSolutions( ...
    projFolderPath, ...
    'solutions', solname, ...
    'timesteps', timesteps, ...
    'showGhost', false, ...
    'zlimits', false, ...
    'view2d', true, ...
    'movie', false, ...
    'KtoC', solname == "theta", ...
    'contour', true, ...
    'snow', false);

%% Plot snow

closeall

projFolderPath = "/Users/chuckjia/Documents/Workspace/Git/weather/";

Dt = 0.5;
Nt = 200;

timesteps = 0:Dt:Nt*Dt;

plotSnow( ...
    projFolderPath, ...
    'timesteps', timesteps, ...
    'zlimits', false, ...
    'contour', true, ...
    'movie', false);
