
%% Plot solution

closeall

projFolderPath = "/Users/chuckjia/Documents/Workspace/Git/weather/";
solParams

solnameArray = ["theta", "qv", "qc", "qp"];
zlimitsArray = {[-40, 22], [0, 10], [0, 0.035], [0, 0.05]};
zlimitsMap = containers.Map(solnameArray, zlimitsArray);

solname = "qp";
zlimits = zlimitsMap(solname);

timesteps = default_timesteps;
% timesteps = 0;


plotSolutions( ...
    projFolderPath, ...
    'solutions', solname, ...
    'timesteps', timesteps, ...
    'showGhost', false, ...
    'zlimits', zlimits, ...
    'view2d', false, ...
    'movie', false, ...
    'zoom', 1, ...
    'KtoC', solname == "theta", ...
    'contour', true, ...
    'snow', true);

%% Plot snow

closeall

projFolderPath = "/Users/chuckjia/Documents/Workspace/Git/weather/";
solParams

zoom = 0.8;
zlimits = [0, 0.1];

timesteps = 5000;

plotSnow( ...
    projFolderPath, ...
    'timesteps', timesteps, ...
    'zlimits', false, ...
    'contour', true, ...
    'movie', false, ...
    'zlimits', zlimits, ...
    'zoom', zoom);
